import { Urbanist } from "next/font/google";
import "./globals.css";


const UrbanistFont = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${UrbanistFont.className}`}>
        {children}
      </body>
    </html>
  );
}
