import { Urbanist } from "next/font/google";
import "./globals.css";
import Providers from "@/components/ThemeProvider";
import AnnouncementBar from "@/components/sections/AnnouncementBar";
import Navbar from "@/components/sections/Navbar";
import Footer from "@/components/sections/Footer";


const UrbanistFont = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${UrbanistFont.className}`}>
        <Providers>
          <AnnouncementBar />
          <Navbar />
          {children}
          <Footer />

        </Providers>

      </body>
    </html>
  );
}
